### ISSUE TITLE
Help with configuring the mock-IdP with Okta (noob question)

### ISSUE THREAD

**Issue by gauravkhot** [OpenConext/Mujina#18]
Would it be possible to use the mock-idp to work with Okta. I am thinking of using this as a starting point for my project. I have gotten to the point where Okta is able to send the redirected login request to the mock-idp but after successful login I am redirected to the user.html page, not back to mysite.okta.com.

Apologies for the completely newbie question.

**Comment by oharsta** [comment]
Could you elaborate on what it is you exactly want to accomplish? The assumption I have made in the answer below is that you want to use Mujina IdP as the external SAML2 Identity Provider for  Okta in the role of SAML Service Provider. 

In order to set this up you'll need to configure the Mujina as a SAML IdP in Okta and after that you'll need to configure the Mujina SAML protocol settings in Okta. Part of the protocol settings is the IdP Single Sign-On Url. This is the starting point of the SAML login. In the SAML authn request initiated by Okta to Mujina there will be a Assertion Consumer Service URL (ACS) which is the redirect URL after a successful login. 

The SAML login flow which is initiated with either a GET or POST to SingleSignOnService of Mujina should not be confused with a direct login to the user.html endpoint. In the first scenario you'll be redirected by the browser to the ACS in the SAML request; in the latter you will be redirected to the endpoint you have requested e.g. user.html.

Mujina is SAML2.0 spec compliant and your question is better asked on the Okta mailing list or you could read the documentation of Okta: https://support.okta.com/help/Documentation/Knowledge_Article/40561903-Configuring-Inbound-SAML#Part1

**Comment by gauravkhot** [comment]
@oharsta Thanks very much for the response. I will take a look at the Okta documentation and follow thru with my question.
