### ISSUE TITLE
Build failure for mujina-idp and mujina-sp

### ISSUE THREAD

**Issue by Hubcrawler** [OpenConext/Mujina#76]
Trying to build latest 7.4.3 release and getting attached error for both:
![image](https://user-images.githubusercontent.com/90420807/132756867-c0b4ffc7-fde7-4918-8175-272b43dc4731.png)

**Comment by tgandhi16** [comment]
Having same issue any recommendations please?

**Comment by oharsta** [comment]
Checked out revision e73e77286577a126f363d4f1bdb94a4e94c4c112 and tagged it with `mujina-7.4.3`. When I run mvn clean install:
```
[INFO] Reactor Summary for mujina 7.4.3:
[INFO] 
[INFO] mujina ............................................. SUCCESS [  0.965 s]
[INFO] mujina-common ...................................... SUCCESS [  2.732 s]
[INFO] mujina-sp .......................................... SUCCESS [ 17.365 s]
[INFO] mujina-idp ......................................... SUCCESS [ 14.135 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```
@tgandhi16 Can you send me the command you are using including the stack-trace and provide me with details with regards to your environment? You must start the build from the root folder (e.g. not in mujina-sp), because otherwise mujina-common is not installed locally in your ~.m2 repository.

**Comment by tgandhi16** [comment]
Thanks @oharsta  I am doing this via eclipse I would need to get this again using command line all over and see I get ahead with it.
Earlier I did try to build just the IDP which failed as you said. But the entire project build worked however the install was failing after that.

**Comment by tgandhi16** [comment]
The mvn clean install worked using MVN command line, something is up with with my Eclipse MVN plugin that fails to find the repository so I may have get that to work. 
Thank you!
